### ISSUE TITLE
`dogapi` is required  to use Datadog report 

### ISSUE THREAD

**Issue by andromedarabbit** [DataDog/puppet-datadog-agent#129]
I am running Puppet 4.2.2 licenced under the open source. I followed the instruction on this project but Puppet integration on the dashboard says the "No Data Received". After looking into `puppetserver.log`, I found the following error message:

```
[puppet-server] Puppet You need the `dogapi` gem to use the Datadog report (run puppet with puppet_run_reports on your master)
```

Reporting is now working well since I have installed `dogapi` gem by hand:

```
sudo puppetserver gem install dogapi
```

**Comment by talwai** [comment]
Hi @andromedarabbit , we actually document this in our [README](https://github.com/DataDog/puppet-datadog-agent/blob/master/README.md)
> To support reporting, your Puppet master needs to have the dogapi gem installed, to do that either run the puppet agent on your master with this configuration or install it manually with gem

Let us know if there's anything that can be made clearer in the docs. Closing this
