### ISSUE TITLE
HTTPS is not yet a thing for the datadog repo

### ISSUE THREAD

**Issue by nick-parry** [DataDog/puppet-datadog-agent#133]
It seems that ssl repo support has not yet been deployed by datadog. Meaning that our AMIs were failing and we didn't know why. I found that on the 7th, it was changed to https. Here is what port 443 returns from this url as of today(10-09-15):
```
nick.parry@nparry-laptop:~$ nc -vzw2 yum.datadoghq.com 443
nc: connect to yum.datadoghq.com port 443 (tcp) failed: Connection refused
```
Just wanted to provide some visibility on this issue.

**Comment by kennyg** [comment]
this is a problem for me too and is blocking many deployments. please fix.

**Comment by talwai** [comment]
Hey @nick-parry @kennyg , thanks for reporting this. This should actually be fixed now, since we enabled HTTPS on our package repos. Here's what I see as of 10-21-15:
```
$ nc -vzw2 yum.datadoghq.com 443
Connection to yum.datadoghq.com 443 port [tcp/https] succeeded!
$ nc -vzw2 apt.datadoghq.com 443
Connection to apt.datadoghq.com 443 port [tcp/https] succeeded!
```

Will leave this issue open for a bit, so you guys can report back on whether you're still having problems

**Comment by nick-parry** [comment]
I can confirm what you are seeing. This issue can be closed. Thanks.
```
nick@nickp-laptop1:~$ nc -zvw2 yum.datadoghq.com 443 
Connection to yum.datadoghq.com 443 port [tcp/https] succeeded!
```
