### ISSUE TITLE
module has wrong dependency for stdlib in metadata.json

### ISSUE THREAD

**Issue by mrunkel** [DataDog/puppet-datadog-agent#146]
metadata.json indicates that any 4.x version of stdlib is sufficient, but the use of validate_integer means it's not.

We have 4.5.1 installed currently which doesn't have the validate_integer function.

Please correct your metadata.json file to reflect the minimum version of stdlib that includes validate_integer.   It looks like v4.6 is what you want.

**Comment by kitchen** [comment]
could you turn this into a PR? :)

**Comment by mrunkel** [comment]
Done.

**Comment by truthbk** [comment]
@mrunkel thanks a lot for this!

**Comment by PolaricEntropy** [comment]
Close this since it's implemented?
