### ISSUE TITLE
Missing integration for Consul

### ISSUE THREAD

**Issue by gozer** [DataDog/puppet-datadog-agent#157]
Now that consul is supported in datadog, would be nice if this puppet module exposed that fact

**Comment by bflad** [comment]
In case you haven't seen, there's a pending PR: https://github.com/DataDog/puppet-datadog-agent/pull/153

**Comment by truthbk** [comment]
@gozer thanks for bringing this up. This will be addressed in out next release. Thanks for noting it, and for your patience :)

**Comment by truthbk** [comment]
Sorry for not closing this guy sooner - this was indeed addressed in #176 courtesy of @flyinprogrammer Thanks for your patience.
