### ISSUE TITLE
Allow modifications to reported hostnames

### ISSUE THREAD

**Issue by handigarde** [DataDog/puppet-datadog-agent#160]
Related to https://github.com/DataDog/puppet-datadog-agent/issues/1

Hosts may show up as duplicates in infrastructure list, with puppet metrics only intermittently reporting. Some cases have included a workaround specific to each case, but these workarounds need to be included each time the puppet module is updated

**Comment by olivielpeau** [comment]
We have a patch that allows applying a regex to the hostnames reported by puppet: https://gist.github.com/LeoCavaille/264d0f7cf27b0d7e2bb3.

It's a good approach for simple cases, but we should investigate if it could be improved on or if we could use another approach.

**Comment by ee99ee** [comment]
:+1:

**Comment by aruetten** [comment]
We had a similar issue and used in the end the following patch:
```diff
@@ -13,6 +13,12 @@ Puppet::Reports.register_report(:datadog_reports) do
   raise(Puppet::ParseError, "Datadog report config file #{configfile} not readable") unless File.exist?(configfile)
   config = YAML.load_file(configfile)
   API_KEY = config[:datadog_api_key]
+  HOSTNAME_EXTRACTION_REGEX = config[:hostname_extraction_regex]
+  unless HOSTNAME_EXTRACTION_REGEX.empty?
+      HOSTNAME_EXTRACTION_REGEX = Regexp.new HOSTNAME_EXTRACTION_REGEX
+  else
+      HOSTNAME_EXTRACTION_REGEX = nil
+  end
 
   desc <<-DESC
   Send notification of metrics to Datadog
@@ -38,6 +44,12 @@ Puppet::Reports.register_report(:datadog_reports) do
   def process
     @summary = self.summary
     @msg_host = self.host
+    unless HOSTNAME_EXTRACTION_REGEX.nil?
+        m = @msg_host.match(HOSTNAME_EXTRACTION_REGEX)
+        unless m[1].nil?
+            @msg_host = m[1]
+        end
+    end
 
     event_title = ''
     alert_type = ''
```

and the following regexp `'^(.*?)\.'`

**Comment by diranged** [comment]
This is a great patch -- I'd love to see it pushed to the project so we can use it without forking the project ourselves.

**Comment by LeoCavaille** [comment]
@diranged I can try to rebase that to apply it to the current master. Will open a PR.
