### ISSUE TITLE
When puppetserver, install dogapi into puppetserver context

### ISSUE THREAD

**Issue by nrvale0** [DataDog/puppet-datadog-agent#167]
If using POSS w/ puppetserver or Puppet Enterprise the 'dogapi' gem must be installed into the context of puppetserver(JRuby):

```ShellSession
# /opt/puppetlabs/bin/puppetserver gem install dogapi
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: dogapi-1.21.0.gem (100%)
Successfully installed dogapi-1.21.0
2 gems installed
# /etc/init.d/pe-puppetserver restart
```

**Comment by Sher-Chowdhury** [comment]
To get puppet reporting working I also had to do:


`
$ /opt/puppetlabs/bin/puppetserver gem install puppet
`
I also had to manually copy the following file:

https://github.com/DataDog/puppet-datadog-agent/blob/master/lib/puppet/reports/datadog_reports.rb

and drop it into the following directory on my puppetmaster:

/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/reports

**Comment by brainonmute** [comment]
With Puppet Labs recommending the POSS Puppet Collection methodology as the best installation method, this module should be updated to reflect that. [https://puppet.com/blog/welcome-to-puppet-collections](url)

**Comment by truthbk** [comment]
Thanks for bringing this up @nrvale0, @Sher-Chowdhury and @brainonmute. Much appreciated. Will let you guys know when we merge a fix.

**Comment by truthbk** [comment]
With #188 we should now be choosing the correct gemprovider depending on the puppet version, and dogapi should now fall into the right environment in either case. Tested it successfully, and this was out with the `1.7.1` bugfix release we made yesterday. Thanks a lot for bringing this up. Also take a look at the updated README.md if you need some more info to get reporting up and running.
