### ISSUE TITLE
Version 1.7.0. defaults `use_dogstatsd` to false

### ISSUE THREAD

**Issue by Ricky-Thomas** [DataDog/puppet-datadog-agent#184]
Customer reached out with an issue where they upgraded the module to 1.7.0. and they immediately stopped seeing their statsd metrics. 

Looks like this is the culprit. https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/init.pp#L219

**Comment by truthbk** [comment]
Thanks @Ricky-Thomas - this should be addressed in PR #183, we'll get that merged soon.

**Comment by truthbk** [comment]
Should be fixed in the latest `1.7.1` bugfix release we made yesterday - it's now enabled by default. Closing for now.
