### ISSUE TITLE
Logic in datadog.yaml is incorrect

### ISSUE THREAD

**Issue by davejrt** [DataDog/puppet-datadog-agent#190]
The following needs to be changed, as it currently is it doesn't work when passing in a value that isn't nil:

<% if @hostname_extraction_regex.nil? -%>
:hostname_extraction_regex: '<%= @hostname_extraction_regex %>'
<% end -%>

to:

<% if !@hostname_extraction_regex.nil? -%>
:hostname_extraction_regex: '<%= @hostname_extraction_regex %>'
<% end -%>

**Comment by truthbk** [comment]
Thanks a lot for opening this and your PR. It was merged into the `1.7.1` bugfix release we made earlier today. We appreciate the contribution!
