### ISSUE TITLE
hiera support?

### ISSUE THREAD

**Issue by 030** [DataDog/puppet-datadog-agent#196]
It would be great if the API key could be defined in hiera

**Comment by NoodlesNZ** [comment]
It can, if you do:

`datadog_agent::api_key: 'apikeyhere'`

Then when you do:

`class { 'datadog_agent' : }`

Then it should pick up the api key from hiera

**Comment by truthbk** [comment]
Indeed, thanks for posting this @NoodlesNZ. We've had hiera support for a while. I'll close this for now as the description is accurate.
