### ISSUE TITLE
Service enable on Centos

### ISSUE THREAD

**Issue by tokozedg** [DataDog/puppet-datadog-agent#199]
Each time puppet  run this module on Centos, it re-enables service, which by itself triggers false "changed" puppet report on a node:
```
Debug: Executing: '/bin/systemctl is-active datadog-agent'
Debug: Executing: '/bin/systemctl show datadog-agent --property LoadState --property UnitFileState --no-pager'
Debug: Executing: '/bin/systemctl unmask datadog-agent'
Debug: Executing: '/bin/systemctl enable datadog-agent'
Notice: /Stage[main]/Datadog_agent::Redhat/Service[datadog-agent]/enable: enable changed 'false' to 'true'
```

I find setting `provider => 'redhat'` in `redhat.pp` solves this problem.

**Comment by truthbk** [comment]
@tokozedg thanks for sharing this with us. I will verify and hopefully merge a fix soon! 👍

**Comment by truthbk** [comment]
https://github.com/DataDog/puppet-datadog-agent/pull/222

**Comment by truthbk** [comment]
@tokozedg The latest module is out `1.8.1` and should allow handling this fine. Please reopen if you find any issues. 

Thanks!
