### ISSUE TITLE
datadog_agent::integrations::cassandra not available in v1.7.1

### ISSUE THREAD

**Issue by pchristopher1275** [DataDog/puppet-datadog-agent#218]
Hey y'all; hope that this is the right forum to post this "issue". We would like to use the cassandra integration with datadog, sadly it appears that the cassandra functionality was checked in Jun 22 (https://github.com/DataDog/puppet-datadog-agent/commits/master/manifests/integrations/cassandra.pp), but 1.7.1 was released Jun 21 (https://forge.puppet.com/datadog/datadog_agent). We would love to incorporate this functionality into our setup. Are we reasonably close to the next release? If not, what is the easiest way for us to bring that functionality into our operation? Thanks for any feedback.

**Comment by truthbk** [comment]
@pchristopher1275 these'll be available in the next release, coming your way early next week (starting 08/08) - sorry for the wait.

**Comment by pchristopher1275** [comment]
Thanks for the info Jaime. -Pete

**Comment by truthbk** [comment]
@pchristopher1275 the release is out - `1.8.1` should have what you need.
