### ISSUE TITLE
Puppet Server 4.x requires manual installation of `puppetserver_gem`

### ISSUE THREAD

**Issue by sjenriquez** [DataDog/puppet-datadog-agent#250]
The Datadog module requires the `dogapi` ruby package. On Puppet Server 4.x, if `puppetserver_gem` is not already installed, the `dogapi` package will not install and cause reporting to fail with the error:

```
You need the `dogapi` gem to use the Datadog report (run puppet with puppet_run_reports on your master)
```

To install `puppetserver_gem` run:

```
puppet module install puppetlabs-puppetserver_gem
```

Older versions of Puppet use `gem` instead of `puppetserver_gem` to install packages. The gem provider can be configured on this line:
https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/init.pp#L187

**Comment by truthbk** [comment]
As discussed this is a problem, but getting around it and still supporting older puppets is a bit of an issue. Still working on this one....

**Comment by bittner** [comment]
Please drop support for Puppet < 3 and fix this issue.

**Comment by bittner** [comment]
> getting around it and still supporting older puppets is a bit of an issue

@truthbk, can you explain the problem a bit more in detail? Maybe the community can help.

**Comment by bittner** [comment]
I install [puppetserver_gem v1.0.0](https://forge.puppet.com/puppetlabs/puppetserver_gem) with my control repo on my Foreman host. When my clients try to perform an installation I get the following error:

```
Package[dogapi]: Provider puppetserver_gem is not functional on this host
```

What does this mean? The `puppetserver_gem` module is regularly deployed and available on the host along with all other modules `r10k` has deployed.

**Comment by bittner** [comment]
I fixed the `puppetserver_gem` by installing and configuring [system_gem](https://forge.puppet.com/tkishel/system_gem) in [init.pp](https://github.com/comsolit/puppet-datadog-agent/blob/master/manifests/init.pp#L197) (line 197). Not sure why `puppetserver_gem` isn't installed correctly when specified in the module dependencies.

**Comment by truthbk** [comment]
`puppetserver_gem` is now a real dependency after the `2.x` release, not a soft-one as it used to be with the legacy module. The module will be installed, and `dogapi-rb` will be installed automatically, however to be picked up I have had to restart the `puppetserver`. 

Closing this as it no longer holds true for the newer puppet module releases.
