### ISSUE TITLE
DATADOG_RPM_KEY.public broken on CentOS 6

### ISSUE THREAD

**Issue by nkonopinski** [DataDog/puppet-datadog-agent#277]
Centos 6 (ruby 1.8.7, puppet 2.7, OpenSSL 1.0.1e-fips 11 Feb 2013) doesn't seem to support the TLS connections necessary by the remote_file module. yum.datadoghq.com only supports TLS. I receive this error when I try to install the module:

err: /Stage[main]/Datadog_agent::Redhat/Remote_file[DATADOG_RPM_KEY.public]/ensure: change from absent to present failed: Could not set 'present on ensure: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure at /etc/puppet/modules/puppet-datadog-agent/manifests/redhat.pp:37

**Comment by truthbk** [comment]
@nkonopinski thank you for bringing this up. I believe this is a ruby issue, or more specifically related to how the ruby on the box. It's a very old ruby, actually an EOL'd ruby (two and half years ago) - so we'll see what we can do about that. Your best bet would be to update ruby, but that could have side-effects on your puppet installation... so if you decide to attempt that, proceed with caution. Regardless I will try to reproduce on a similarly spec'd box, thank you very much for the version details. Hopefully we can post a fix here, or in code, soon. Thank you for letting us know! 🙇

**Comment by truthbk** [comment]
Also, just so you know @nkonopinski, it's probably a good idea if you don't use that ruby for anything critical as it's likely that it's susceptible to certain TLS/SSL attacks (ie. poodle, heartbleed, etc).

**Comment by xunnanxu** [comment]
👍

**Comment by xunnanxu** [comment]
@truthbk I believe the fix is to turn on TLSv1 or above for remote_file module in terms of SSL connections. Right now ruby defaults only enable SSLv23 which are already not supported by a lot of servers. https://github.com/ruby/ruby/blob/trunk/ext/openssl/lib/openssl/ssl.rb

```
class datadog_yum_repo_without_gpg {
     yumrepo {'datadog':
       enabled  => 1,
       gpgcheck => false,
       descr    => 'Datadog, Inc.',
       baseurl  => "https://yum.datadoghq.com/rpm/${::architecture}/",
     }
 }

    class { 'datadog_agent':
      require datadog_yum_repo_without_gpg
      manage_repo         => false,
    }
```

**Comment by mmarkov** [comment]
And server actually "says" - "What is SSL?"
```
Nmap scan report for yum.datadoghq.com (54.192.119.165)
Host is up (0.0074s latency).
Other addresses for yum.datadoghq.com (not scanned): 54.192.119.92 54.192.119.61 54.192.119.214 54.192.119.236 54.192.119.134 54.192.119.60 54.192.119.53
rDNS record for 54.192.119.165: server-54-192-119-165.sfo9.r.cloudfront.net
Not shown: 998 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C
```
Thanks @xunnanxu , workaround works for me.

**Comment by zyymorning** [comment]
I had the same problem and I removed the part which tries to download the remote datadog key. This part also looks unnecessary to me since the gpgkey used in yumrepo is the old gpg key https://github.com/DataDog/puppet-datadog-agent/pull/283/files.

**Comment by truthbk** [comment]
Sorry for the slow final response to this issue. 

So the suggestion by @xunnanxu of enforcing a stronger protocol is actually already implicit in the way openssl works. You may take a look at the official openssl [documentation](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_new.html). `SSLv23` is what's considered a "maximum interoperability" mode, that doesn't mean SSLv3 or v2 are enforced over any other secure transport layer. What it means is that OpenSSL will try to go from TLSv1.2 down to TLSv1.1, TLSv1, etc to SSLv2 from stronger to weaker, trying to find something appropriate that both server and client speak. Indeed our server does not speak anything <`TLSv1.0`, so if your particular puppet/ruby setup does not support TLS you're out of options and will have to disable the `gpgcheck` on the repository. 

This is not a bug, and should not be considered so. If you, understandably, want to enable the gpgcheck, I strongly advise you update your ruby/openssl/puppet setup.

I will be closing this issue, as the discussion/outcome seems clear.

Thank you guys for your patience.
