### ISSUE TITLE
Docker service discovery permissions issue

### ISSUE THREAD

**Issue by kimgust** [DataDog/puppet-datadog-agent#301]
I'm running into what appears to be a 🐔 and :egg: issue with the service discover params in the datadog_agent puppet class. My class is:

```
  class { 'datadog_agent':
    api_key => $dd_api_key,
    log_level => 'debug',
    service_discovery_backend => 'docker',
    sd_config_backend => 'etcd',
    sd_backend_host => $etcd_host,
    sd_backend_port => $etcd_port,
  }
```

In the error logs I see:

```
DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
```

Turns out the dd-agent user is not in the docker group:

```
$ groups dd-agent
dd-agent : dd-agent
```

This makes sense, as I forgot to include the docker_daemon integration which [takes care of this](https://github.com/DataDog/puppet-datadog-agent/blob/94473abbea31d89aa1443b33d72d6979b7a6c680/manifests/integrations/docker_daemon.pp#L29-L34). So:

```
  class { 'datadog_agent':
    api_key => $dd_api_key,
    log_level => 'debug',
    service_discovery_backend => 'docker',
    sd_config_backend => 'etcd',
    sd_backend_host => $etcd_host,
    sd_backend_port => $etcd_port,
  }

  class { 'datadog_agent::integrations::docker_daemon':
    before => Class['datadog_agent'],
  }
```

But the integration relies on the class:

```
Error: Could not apply complete catalog: Found 1 dependency cycle:
(File[/etc/dd-agent/conf.d/docker.yaml] => Class[Datadog_agent::Integrations::Docker_daemon] => Class[Datadog_agent] => File[/etc/dd-agent] => File[/etc/dd-agent/conf.d/docker.yaml])
```

The way I've resolved this for now is to comment out the service discover lines from the datadog_agent class, apply changes, and add them back and apply again.

**Comment by truthbk** [comment]
Thanks a lot for bringing this into our attention @kimgust. We'll look into it as soon as possible.

Thanks again 🙇
