### ISSUE TITLE
Puppet fails to run with 1.10.0: dd-agent is not a valid user

### ISSUE THREAD

**Issue by jbuck** [DataDog/puppet-datadog-agent#324]
When attempting to a deploy a service today using 1.10.0 I received the following error message from puppet: `Error: Parameter owner failed on Concat[/etc/dd-agent/datadog.conf]: dd-agent is not a valid user at /etc/puppet/modules/datadog_agent/manifests/init.pp:388`.

When I pinned the puppet-datadog-agent dependency to 1.9.0 puppet ran successfully.

Happy provide any more information for debugging purposes

**Comment by truthbk** [comment]
@jbuck thanks for bringing this up.... Could you please share with me the offending manifest? I've been trying to reproduce with no luck.

**Comment by jbuck** [comment]
Hi @truthbk, after I was able to spend a more time investigating this issue I discovered that we had a custom version of the concat plugin that didn't implictly create users like the forge plugin does. When I removed our custom version and replaced it with the forge plugin installing puppet-datadog-agent v1.10.0 worked correctly.

My apologies for the noise, and have a great day!
