### ISSUE TITLE
docker_daemon.yaml.erb results in invalid yaml when tags are present

### ISSUE THREAD

**Issue by ckolos** [DataDog/puppet-datadog-agent#337]
As stated, when tags are set in the calling manifest, too much whitespace is added to the tags: section and this breaks the yaml created by the template.

PR is waiting for review/merge here: [336](https://github.com/DataDog/puppet-datadog-agent/pull/336)

**Comment by truthbk** [comment]
Thanks a ton for the fix @ckolos merged the PR 👍
