### ISSUE TITLE
utf-8 'smart quotes' in manifests/integrations/jmx.pp breaks puppet-lint

### ISSUE THREAD

**Issue by mattghali** [DataDog/puppet-datadog-agent#349]
Hi folks; the quotes on https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/integrations/jmx.pp#L25 break puppet-lint. Might want to convert them to plain single quotes?

thanks!

**Comment by truthbk** [comment]
@mattghali thank you for the feedback - this will be addressed in the next release. Thank you, and sorry for letting this one slip through.
