### ISSUE TITLE
No way to set a proxy for initial setup (e.g. fetching of GPG key)

### ISSUE THREAD

**Issue by leitmedium** [DataDog/puppet-datadog-agent#354]
Initial setup via puppet fails when you need to rely on outgoing proxy for any http traffic. The GPG key is being fetched by remote_file call which does not pass proxy settings. 

Quick work around: use another / manual way to put the GPG key to /etc/pki/rpm-gpg/DATADOG_RPM_KEY.public 

Intended solution: You should be able to pass proxy settings for any http call.

**Comment by truthbk** [comment]
Thank you for your feedback and the breakdown of the issue @leitmedium

We'll take a look at this as soon as we have the bandwidth, and can hopefully address it for the next release. Very much appreciated! 🙇

**Comment by truthbk** [comment]
I am sorry this didn't make it into the initial `2.0` module. Luckily `remote_file` supports proxy settings and we will enable this starting with `2.2.0`

**Comment by truthbk** [comment]
We eventually moved away from `remote_file` to `apt` for the entire key management for the `apt` repository. `apt` does allow passing options, including an http proxy. `apt` might already enforce proxy settings defined for a particular box, btw. But we'll look at the possibility of making it explicit.
