### ISSUE TITLE
Unknown resource type: 'remote_file'

### ISSUE THREAD

**Issue by gennady-voronkov** [DataDog/puppet-datadog-agent#365]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'remote_file' at /etc/puppetlabs/code/environments/production/modules/datadog_agent/manifests/redhat.pp:30:5

**Comment by gennady-voronkov** [comment]
puppetserver -v
puppetserver version: 2.7.2

**Comment by ardrigh** [comment]
Install the `remote_file` module 

https://forge.puppet.com/lwf/remote_file

**Comment by truthbk** [comment]
This isn't a requirement anymore with the `2.x` module series. Closing this one. Thanks @ardrigh for your help :)
