### ISSUE TITLE
ubuntu::install_key should not continuously install repository keys

### ISSUE THREAD

**Issue by bittner** [DataDog/puppet-datadog-agent#367]
We manage hosts running Debian 8.9, and we notice that Puppet is executing the following statements continuously, i.e. on every single Puppet run, every 30 minutes:

```puppet
/Stage[main]/Datadog_agent::Ubuntu/Datadog_agent::Ubuntu::Install_key[935F5A436A5A6E8788F0765B226AE980C7A7DA52]/Exec[key 935F5A436A5A6E8788F0765B226AE980C7A7DA52]/returns
executed successfully
/Stage[main]/Datadog_agent::Ubuntu/Datadog_agent::Ubuntu::Install_key[A2923DFF56EDA6E76E55E492D3A80E30382E94DE]/Exec[key A2923DFF56EDA6E76E55E492D3A80E30382E94DE]/returns
executed successfully
```
There are two issues with this:
1. This happens on plain Debian, not Ubuntu. So, either **the feature or the naming** is broken.
1. Installing the key should not execute again, it **shouldn't show up** in the Puppet agent log.

The latter is most probably related to [manifests/ubuntu/install_key.pp, line 18](https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/ubuntu/install_key.pp#L18).

**Comment by bittner** [comment]
The problem with the `grep` statement at [manifests/ubuntu/install_key.pp, line 18](https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/ubuntu/install_key.pp#L18) is that `apt-key list` does _not_ list the long keys (aka "fingerprints"). Hence the grep one-liner must use `apt-key finger` instead, and use a humanized key fingerprint for grepping, e.g.

```bash
$ apt-key finger | grep -B1 "A292 3DFF 56ED A6E7 6E55  E492 D3A8 0E30 382E 94DE"

**Comment by bittner** [comment]
@DataDog Anyone commenting on this?

**Comment by szponek** [comment]
In the interim #373 fix works, but why not add a dependency on puppetlabs-apt module and use apt_key resource for these keys instead of an exec?

**Comment by szponek** [comment]
@truthbk any chance of pulling either #350 or #373 to fix this?

**Comment by irabinovitch** [comment]
@szponek Thanks for reaching out.  We'll take a look over the next few days and get back to both PRs with feedback.

**Comment by bittner** [comment]
One of those two PRs should definitely fix the issue. Without any reason for "maybe breaking backward-compatibility".

Please, guys, accelerate a bit. This is so lame. Really frustrating.

**Comment by truthbk** [comment]
Should be addressed in `2.x` - closing. Thanks for the reports @szponek, @bittner

**Comment by bittner** [comment]
@truthbk Could you point to the commit that fixed that, please? Thank you.

**Comment by tdm4** [comment]
We're stuck on an older version of datadog_agent (thanks to some puppet dependencies), and we get this. However, there's something about `/etc/apt/trusted.gpg`.. this happens on some Ubuntu 18.04 hosts but not others. Copying the `/etc/apt/trusted.gpg` from a machine that doesn't continually re-add the Datadog key to a machine that does.. resolves it..but I'm not entirely sure why.

Is it a keys trust issue?

**Comment by tdm4** [comment]
I did some more digging. I think it's actually a bug in apt::key (Puppetlabs-apt) but we're stuck on v2.4.0 (and v7.0.1 is out) due to old puppet dependencies.

It looks like the apt_key.rb file was completely rewritten and this problem appears to occur when there are more than *2* keys in /etc/apt/trusted.gpg (and Datadog's key is one of them)

More than 2 keys in that file and the apt  module never "finds" the key so it adds it.. over and over again.
