### ISSUE TITLE
Support for Logs

### ISSUE THREAD

**Issue by NoodlesNZ** [DataDog/puppet-datadog-agent#382]
Is it possible to have the puppet module support Datadog Logs? I've been looking forward to trying the Logs beta, but any manual changes to the server will be overwritten by puppet.

**Comment by irabinovitch** [comment]
@NoodlesNZ We're working on a few updates to the Puppet manifests, including adding logs support. I would expect logs to land before the end of this month.

**Comment by NoodlesNZ** [comment]
Any update here? I saw that 2.2.0 was released a week ago, but I don't see any commits around logs yet.

**Comment by NoodlesNZ** [comment]
Seems to be resolved in #439
