### ISSUE TITLE
Add network_latency_checks to consul module

### ISSUE THREAD

**Issue by Aramack** [DataDog/puppet-datadog-agent#393]
The datadog integration for consul supports monitoring for network latency:
https://github.com/DataDog/integrations-core/blob/master/consul/conf.yaml.example#L42
```
      # Whether to enable network latency metrics collection. When enabled
      # consul network coordinates will be retrieved and latency calculated for
      # each node and between data centers.
      # See https://www.consul.io/docs/internals/coordinates.html
      network_latency_checks: yes
```

This is not exposed through the puppet module:
https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/integrations/consul.pp#L29
https://github.com/DataDog/puppet-datadog-agent/blob/master/templates/agent-conf.d/consul.yaml.erb#L31

**Comment by truthbk** [comment]
Thank you for your work @Aramack this will be going out with `2.1.0`
