### ISSUE TITLE
Make the integration manifests 'parameter agnostic'

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/puppet-datadog-agent#40]
It's a pain to have to specify every key of the YAML file in a different variable.
We could just get a dictionary representing the instances and convert it to YAML.

``` ruby
class { 'datadog_agent::integrations::example' :
  instances => [
    { 'host' => 'localhost', 'port' => 42, 'tags' => [] }
  ]
}

# in the template
<%= require 'yaml'; {'init_config'=>@init_config, 'instances'=>@instances}.to_yaml %>
```

Moreover, it would be easy to add new integrations, the puppet user just has to stick to the description format of the agent YAML file.

cc @alq666 

That potentially is a non backward-compatible change for people manifests tough.

**Comment by albertvaka** [comment]
We are already doing this for new stuff but I don't think it's worth refactoring all the existing integrations. Closing.
