### ISSUE TITLE
Add support for older versions of puppetlabs/apt

### ISSUE THREAD

**Issue by samueljamesmarshall** [DataDog/puppet-datadog-agent#400]
Affected version: 2.0.0

Many other forge modules that depend on "puppetlabs/apt" have a version requirement of ">= 1.8.0 < 3.0.0".

Please add support for at least puppetlabs/apt 2.4.0 to meet the dependency version requirements for dozens of other forge modules.

I'd say the majority of people using many/multiple forge modules (particularly those relying on librarian-puppet to resolve and install module dependencies) will not be able to upgrade to datadog/datadog_agent 2.0.0 without this.

**Comment by truthbk** [comment]
I will look into this and see if we can drop that lower dependency bound without breaking anything. Sorry for the inconvenience.

**Comment by truthbk** [comment]
Lowered lower `puppetlabs/apt` version bound to `2.4.0` for increased compatibility in #404 - Thanks @samueljamesmarshall
