### ISSUE TITLE
MySQL integration should not require password parameter

### ISSUE THREAD

**Issue by thebearmayor** [DataDog/puppet-datadog-agent#409]
https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/integrations/mysql.pp requires a password parameter (no default) even when passed instances. When instances are specified, they have their own password parameters, and the top-level parameter is not used. In addition, it was recently changed to validate specifically as a String, breaking any users who passed `undef` for clarity.

**Comment by truthbk** [comment]
@thebearmayor thank you for reporting this.

**Comment by thebearmayor** [comment]
I intended to submit a fix for this myself, but I checked out the code, ran `rake spec` and got hundreds of failures. Is that normal?
