### ISSUE TITLE
How to upgrade to dd-agent V6 using puppet

### ISSUE THREAD

**Issue by obenziane2** [DataDog/puppet-datadog-agent#419]
Does anybody know how to upgrade to datadog-agent V6 using puppet ?

**Comment by truthbk** [comment]
@obenziane2 if you use version `>=2.0` of the puppet-datadog-agent you should get agent6 by default. Does the [README.md](https://github.com/DataDog/puppet-datadog-agent/blob/master/README.md) not help you with the upgrade?

**Comment by truthbk** [comment]
I believe the [README.md](https://github.com/DataDog/puppet-datadog-agent/blob/master/README.md) should address most questions regarding the migration, so closing this.
