### ISSUE TITLE
Host parameter is non-functional.

### ISSUE THREAD

**Issue by pizzaops** [DataDog/puppet-datadog-agent#421]
The parameter `$host` to the `datadog_agent` class has no effect. It's not referenced anywhere in the rest of the code, including templates.

I initially detected this via just attempting to use it, and then verified via manual inspection, various greps, and RubyMine's "find uses" (which supports Puppet fully).

All you need to do to reproduce this is try:

```puppet
class { 'datadog_agent':
  host => 'any.value.at.all',
}
```

and nothing happens. There is no way to override a node's hostname with the current Puppet module, as far as I can tell.

Using latest stable version, 2.1.1.

**Comment by truthbk** [comment]
Thanks for reporting this @pizzaops we'll take a look

**Comment by marcomusso** [comment]
[This](https://github.com/marcomusso/puppet-datadog-agent/commit/e73a72445e82fa2f0b449a209c0be2b50f69f6e2) works for me on Puppet 3.x (on 1.12.1).

**Comment by marcomusso** [comment]
A was going to submit a PR but against which branch? Which model are you using to support both versions?

**Comment by truthbk** [comment]
Sorry this took forever. Merged. Will release an updated module soon.
