### ISSUE TITLE
Dependency cycle

### ISSUE THREAD

**Issue by jlintz** [DataDog/puppet-datadog-agent#423]
After upgrading to module version 2.1.1 on a clean bootstrap of an instance for us, we're seeing the following error

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Exec[apt_update] => Class[Apt::Update] => Package[apt-transport-https] => Apt::Source[datadog6] => Apt::Setting[list-datadog6] => File[/etc/apt/sources.list.d/datadog6.list] => Class[Apt::Update] => Exec[apt_update])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

Our base profile is just including the `datadog_agent` class and passing in API keys via Hiera and including 

```
  datadog_agent::integration { 'network':
    instances => [
      {
        'collect_connection_state' => true,
        'excluded_interfaces'      => [ 'lo', 'lo0' ],
      },
    ]
  }
```

We were previously on an old commit `d8f40d83d0f93aefba77965c73baf7d83e3809c4` and upgraded to address the issue with the Apt key expiring.  Going to try and dig through to see if older versions work

**Comment by jlintz** [comment]
Downgrading to 1.x module resolved this for us

**Comment by ernestm** [comment]
We have the same situation:
`Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/etc/apt/sources.list.d/datadog6.list] => Apt::Setting[list-datadog6] => Apt::Source[datadog6] => Package[apt-transport-https] => Apt::Source[datadog6] => Apt::Setting[list-datadog6] => File[/etc/apt/sources.list.d/datadog6.list])`

We'll try downgrading to 1.12.1 as well and see if it fixes us.

**Comment by ernestm** [comment]
It did!  I guess we'll want to go to v2 at some point, but the time to figure out whatever dependency cycle is in this is a problem.  We'll upload more info so hopefully someone working on the module can replicate and fix it.

**Comment by truthbk** [comment]
@jlintz @ernestm could you guys please provide a detailed list of modules installed when you guys encountered this? Also what puppet version are you guys on? 

I'm sorry you guys are facing this, I had never seen anything like it during our testing prior to the last couple releases.

**Comment by truthbk** [comment]
This should now be fixed after deferring `apt-transport-https` to the `apt` module. Also, want to underline that there was never a cycle in our module, only when used in conjunction with the module named above did we see this behavior (and not consistently). 

Going to close, but please feel free to reopen if you see anything awkward.

**Comment by vaisingh** [comment]
Getting the dependency cycle error:
