### ISSUE TITLE
Service cannot start on old amazon linux

### ISSUE THREAD

**Issue by nleib** [DataDog/puppet-datadog-agent#425]
when using the datadog-agent module on older Amazon version (Amazon Linux AMI 2014.09), the service cannot start correctly.
datadog-agent should be stated using "upstart" (on the old amazon version), where the puppet module tries to start the service using /sbin/service which fails the puppet run.

**Comment by nleib** [comment]
I think its because Amazon Linux uses 'upstart' provider which puppet fails to detect, adding provider to the redhat service resolves this.

under the class "class datadog_agent::redhat::agent6"
~~~ puppet
service { $datadog_agent::params::service_name:
    ensure    => $service_ensure,
    enable    => $service_enable,
    hasstatus => false,
    pattern   => 'dd-agent',
    **provider => $datadog_agent::params::service_provider** (should be upstart in amazon linux and undef on the rest.)
    require   => Package[$datadog_agent::params::package_name],
  }
~~~

**Comment by davidgibbons** [comment]
I just was hit by this as well and this is the same solution I've come up with.

**Comment by RainbowHackerHorse** [comment]
This is actually still an issue with the latest RHEL6-based Amazon Linux AMIs, so I'm rather glad to see someone else already did the work I was about to dedicate today to 👍 👍

**Comment by Halt12** [comment]
Hello,
when are you going to merge the PR #425?

**Comment by truthbk** [comment]
https://github.com/DataDog/puppet-datadog-agent/pull/444 was merged instead - should address the problem by allowing the override of the service provider.
