### ISSUE TITLE
Ability to send version of the datadog agent

### ISSUE THREAD

**Issue by nleib** [DataDog/puppet-datadog-agent#434]
Hey,
It would be nice to add the ability to send version of the datadog package.
```puppet
class { 'datadog_agent::redhat::agent6':
          baseurl        => $agent6_repo_uri,
          manage_repo    => $manage_repo,
          service_ensure => $service_ensure,
          service_enable => $service_enable,
          **agent_version => $agent_version** (this way it can also be removed by sending 'absent')
        }
```
or any other flag that we remove the agent

**Comment by marcomusso** [comment]
BTW: when using 1.12.1 (last tag supporting puppet 3) it will install 6.0.3... because the yum repo is pointing to the beta version URL. I fixed that in my fork but I'm waiting on instruction on how to do a PR. But I suppose this fixes will not be backported for an old puppet version.

**Comment by truthbk** [comment]
`agent_version` has been supported since `2.3.0` https://github.com/DataDog/puppet-datadog-agent/pull/447 - I hope that helps. Closing, thank you!
