### ISSUE TITLE
facts_to_tags not working on agent6

### ISSUE THREAD

**Issue by atayts** [DataDog/puppet-datadog-agent#454]
facts_to_tags functionality does not work because of a mistake in datadog_agent::tag6 function. It returns the same list of tags given as arguments instead of tag:value pairs. This should fix it:

```
diff --git a/modules/datadog_agent/functions/tag6.pp b/modules/datadog_agent/functions/tag6.pp
index f2811b6..1ea9607 100644
--- a/modules/datadog_agent/functions/tag6.pp
+++ b/modules/datadog_agent/functions/tag6.pp
@@ -22,7 +22,7 @@ function datadog_agent::tag6(
       if $value =~ Array {
         $tags = prefix($value, "${tag_names}:")
       } else {
-        $tags = [$tag_names]
+        $tags = ["${tag_names}:${value}"]
       }
     } else {
       $tags = [$tag_names]
```

**Comment by mysticmcj** [comment]
Can verify that this is presently broken, and was able to fix with the above patch.

**Comment by truthbk** [comment]
This was merged here: https://github.com/DataDog/puppet-datadog-agent/pull/455 a while back and is currently fixed. Closing!
