### ISSUE TITLE
Managing Yaml files

### ISSUE THREAD

**Issue by satssin** [DataDog/puppet-datadog-agent#458]
Hi Support Team,
How do you manage the  various yaml[Disk, process etc] files via this module?

**Comment by truthbk** [comment]
Please feel free to reach out to our support team through any of the supported channels to get help with setting the puppet module up. They should be able to help!

 I apologize for the slow response, we probably overlooked this issue as it wasn't reporting any actual bugs with the module. I hope you were able to get the help you needed.
