### ISSUE TITLE
Specify datadog agent version

### ISSUE THREAD

**Issue by etamponi** [DataDog/puppet-datadog-agent#461]
Hello,

I would love to be able to specify a datadog agent version in my puppet file. From time to time, when I run puppet, the agent gets updated, and it may break the puppet run, and it causes general slowdown because I am running it on a very busy box.

So, if this is possible, it would be great!

**Comment by truthbk** [comment]
Hi @etamponi this is already possible, just use the `agent_version` parameter: https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/init.pp#L289
