### ISSUE TITLE
reports.pp owns package 'dogapi', does not expose install_options

### ISSUE THREAD

**Issue by skywaymsn** [DataDog/puppet-datadog-agent#539]
The documentation declares the requirement for the dogapi gem, but this CANNOT be installed via puppet because reports.pp tries to force it and you get a resource conflict.

From reports.pp:
`
package{ 'dogapi':
    ensure   => $dogapi_version,
    provider => $puppet_gem_provider,
}
`

This seems great because you don't have to manage the gem yourself, but the implementation does not expose the install_options parameter for the gem provider, and thus prevents the use of proxy servers, etc.

If you need proxies, even with the gem installed, the result is:
`Error: /Stage[main]/Datadog_agent::Redhat::Agent6/File[DATADOG_RPM_KEY.public]: Could not evaluate: Could not retrieve file metadata for https://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public: execution expired`

Please either expose the full suite of options to the dogapi package resource declaration or implement some flag to prevent it from being enforced within reports.pp.

**Comment by PolaricEntropy** [comment]
This should be closed since it's possible to disable management of the dogapi gem as an parameter to reports.pp

https://github.com/DataDog/puppet-datadog-agent/blob/2ea3a5b96ced06e097ac5880ac73939ffd611fab/manifests/reports.pp#L22

**Comment by mx-psi** [comment]
I agree, thanks for bringing it up @PolaricEntropy :)
