### ISSUE TITLE
`Warning: validate_legacy(validate_string) expects a String value, got Undef`

### ISSUE THREAD

**Issue by tokyowizard** [DataDog/puppet-datadog-agent#549]
I upgraded from 2.6.0 to 2.7.0 and suddenly got this warning.

```
Warning: validate_legacy(validate_string) expects a String value, got Undef at ["/var/puppet/vendor/modules/datadog_agent/manifests/init.pp", 362]:["/var/puppet/modules/common/manifests/init.pp", 9]
   (location: /var/puppet/vendor/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
```

Line 9 in my `common/manifests/init.pp` file simply includes datadog:
```
  include common::datadog
```

I have not set `additional_checksd` while using 2.6.0 and 2.7.0.
It's set to `undef` [here](https://github.com/DataDog/puppet-datadog-agent/blob/2.7.0/manifests/init.pp#L266)
But checking if it's a String [here](https://github.com/DataDog/puppet-datadog-agent/blob/2.7.0/manifests/init.pp#L362).
And finally checking if it's set [here](https://github.com/DataDog/puppet-datadog-agent/blob/2.7.0/manifests/init.pp#L646)

This diff seems to resolve the warning when `additional_checksd` is not set.
```
diff --git a/manifests/init.pp b/manifests/init.pp
index 19f7600..c92a568 100644
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -263,7 +263,7 @@ class datadog_agent(
   $use_curl_http_client = false,
   $recent_point_threshold = '',
   $listen_port = '',
-  $additional_checksd = undef,
+  $additional_checksd = '',
   $bind_host = '',
   $use_pup = false,
   $pup_port = '',
@@ -643,7 +643,7 @@ class datadog_agent(
         $statsd_forward_config = {}
     }

-    if $additional_checksd {
+    if $additional_checksd != '' {
         $additional_checksd_config = {
           'additional_checksd' => $additional_checksd,
         }
```

**Comment by albertvaka** [comment]
Thanks for the bug report! This one slipped through when we tested this change...
