### ISSUE TITLE
Error: Found 1 dependency cycle

### ISSUE THREAD

**Issue by vaisingh** [DataDog/puppet-datadog-agent#554]
Getting the dependency cycle error:
I tried fixing it on my local with commenting the require apt line in agent5.pp file
https://github.com/DataDog/puppet-datadog-agent/blob/90ce6434c2c726ea3c2b59aa64022d3ed9c01052/manifests/ubuntu/agent5.pp#L70

Puppet version: 6.7
stdlib version: 5.2
puppet-datadog-agent version: 2.6.0
Can I get any fixed solution for this??

**Comment by danoe** [comment]
I'm seeing this too
Puppet version: 5.5.14
stdlib version: 5.2
puppet-datadog-agent version: 2.7.0
OS: Ubuntu 18.04.1 LTS

Actual error message:
```
(Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present] 
=> Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6] 
=> Apt::Setting[list-datadog6] => File[/etc/apt/sources.list.d/datadog6.list] 
=> Class[Apt::Update] 
=> Exec[apt_update] 
=> Class[Apt::Update]
=> Package[dirmngr]
=> Class[Apt] 
=> Apt::Source[datadog6] 
=> Apt::Setting[list-datadog6])
\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```
Graph output
```
digraph Resource_Cycles {
  label = "Resource Cycles"
"Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt::Setting[list-datadog6]" -> "File[/etc/apt/sources.list.d/datadog6.list]" -> "Class[Apt::Update]" -> "Exec[apt_update]" -> "Class[Apt::Update]" -> "Package[dirmngr]" -> "Class[Apt]" -> "Apt::Source[datadog6]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]"
"Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt::Setting[list-datadog6]" -> "File[/etc/apt/sources.list.d/datadog6.list]" -> "Class[Apt::Update]" -> "Exec[apt_update]" -> "Class[Apt::Update]" -> "Package[dirmngr]" -> "Class[Apt]" -> "Apt::Source[datadog6]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt_key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]"
"Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt::Setting[list-datadog6]" -> "File[/etc/apt/sources.list.d/datadog6.list]" -> "Class[Apt::Update]" -> "Exec[apt_update]" -> "Class[Apt::Update]" -> "Package[dirmngr]" -> "Class[Apt]" -> "Apt::Source[datadog6]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt_key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]"
"Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present]" -> "Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog6]" -> "Apt::Setting[list-datadog6]" -> "File[/etc/apt/sources.list.d/datadog6.list]" -> "Class[Apt::Update]" -> "Exec[apt_update]" -> "Class[Apt::Update]" -> "Package[dirmngr]" -> "Class[Apt]" -> "Apt::Source[datadog6]" -> "Apt::Setting[list-datadog6]"
}
```

**Comment by albertvaka** [comment]
Are you still seeing this problem with recent versions of the module? We haven't had other reports of the problem, so this might be fixed already. Let me know, so I can close the issue :)

**Comment by jippolito-nasuni** [comment]
Am also seeing a dependency cycle error with 
Datadog Puppet Module: 3.3.0
Ubuntu 16.04
Puppet 6.15.0
puppetlabs-stdlib: (v6.3.0)

 ├─┬ datadog-datadog_agent (v3.3.0)
        ├── puppetlabs-ruby (v1.0.1)
        ├── puppetlabs-apt (v7.4.2)
        ├── puppetlabs-puppetserver_gem (v1.1.1)
        ├── puppetlabs-yumrepo_core (v1.0.7)
        └── puppetlabs-powershell (v2.3.0)

Error: Found 1 dependency cycle:
: (Anchor[apt_key A2923DFF56EDA6E76E55E492D3A80E30382E94DE present] => Apt::Key[Add key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE from Apt::Source datadog] => Apt::Setting[list-datadog] => File[/etc/apt/sources.list.d/datadog.list] => Class[Apt::Update] => Exec[apt_update] => Package[gnupg] => Class[Apt] => Apt::Source[datadog] => Apt::Setting[list-datadog])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

Error: Failed to apply catalog: One or more resource dependency cycles detected in graph

Fixed with commenting out in ubuntu.pp:L62:

  apt::source { 'datadog':
    comment  => 'Datadog Agent Repository',
    location => $location,
    release  => $release,
    repos    => $repos,
    **# require  => Class['apt'],**
    key      => $key,
  }
