### ISSUE TITLE
http_check integration is limited to a single instance

### ISSUE THREAD

**Issue by kcampos** [DataDog/puppet-datadog-agent#56]
I'm not sure if this DD feature previously only allowed a single instance, but certainly as of today that isn't the case. Unnecessary limitation.

**Comment by kcampos** [comment]
Yes I think #40 would take care of it.

**Comment by kcampos** [comment]
I take that back. Did some more testing and here's the problem with this design pattern:

`<%= require 'yaml'; {'init_config'=>nil, 'instances'=>@processes}.to_yaml %>`

the keys will keep getting reordered in template causing unnecessary resources changes (same data just reordered in the file). This is why I submitted the PR for sorting keys in the templates previously.

I'm not sure why others haven't brought this up before, but it's important for me that only real resources changes get applied, otherwise our monitoring has false alarms in regards to resources changes occurring outside of code commits. So I'll have to keep this in my fork for now.

**Comment by miketheman** [comment]
@kcampos Why is the data being reordered? This was reported in puppet a while ago, as a Ruby 1.8 only problem. https://projects.puppetlabs.com/issues/16266#note-1

**Comment by kcampos** [comment]
Ah yup, Ruby 1.8 is what I'm on (only by necessity for the time being). I'll just maintain the sorting workaround in my branch for now, which I've been doing for a while. Thx

**Comment by truthbk** [comment]
@kcampos this was addressed in https://github.com/DataDog/puppet-datadog-agent/pull/176, and puppet module `1.7.0`.
