### ISSUE TITLE
Disable metrics

### ISSUE THREAD

**Issue by adeleglise** [DataDog/puppet-datadog-agent#569]
Hi,

Is it possible to manage this https://docs.datadoghq.com/logs/faq/how-to-set-up-only-logs/ without having to manually manage datadog.yaml ?

**Comment by albertvaka** [comment]
While there is no support for this yet, you can use the (undocumented, subject to change specially when agent 7 is released) `agent6_extra_options` that gets merged into the main yaml file.

**Comment by adeleglise** [comment]
Ok thanks, I've successfully managed to apply this configuration with  `agent6_extra_options`.
