### ISSUE TITLE
datadog6 repo missing second gpg key

### ISSUE THREAD

**Issue by devinmatte** [DataDog/puppet-datadog-agent#577]
When the puppet module installs the repo, it misses the second gpg key

```
[datadog]
name=Datadog, Inc.
baseurl=https://yum.datadoghq.com/stable/6/x86_64/
enabled=1
gpgcheck=1
gpgkey=https://yum.datadoghq.com/DATADOG_RPM_KEY.public
```

Instead of 
```
[datadog]
name=Datadog, Inc.
baseurl=https://yum.datadoghq.com/stable/6/x86_64/
enabled=1
gpgcheck=1
gpgkey=https://yum.datadoghq.com/DATADOG_RPM_KEY.public
       https://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public
```

**Comment by albertvaka** [comment]
Thanks for reporting this! It was clearly an oversight on our side. I'm not sure how to specify more than one key in a puppet `yumrepo` resource [1], but we will investigate it. Thanks again :)

[1] https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/redhat/agent6.pp#L49

**Comment by devinmatte** [comment]
For a quick Google it appears you should be able to make a string with a newline containing both keys and it _should_ work. Sadly it doesn't appear like it takes an array as a param

**Comment by albertvaka** [comment]
Nope 😢

```
Error: Parameter gpgkey failed on Yumrepo[datadog6]: Validate method failed for class gpgkey: bad URI(is not URI?): https://yum.datadoghq.com/DATADOG_RPM_KEY.public\n (file: /home/vagrant/puppet/modules/datadog_agent/manifests/redhat/agent6.pp, line: 46)
```

It might be trickier than expected.

**Comment by albertvaka** [comment]
Found the problem. We were already importing the key in a different way, but a change in the output of gpg broke the import. I bet you are on a recent OS with a fairly new gpg version :)

**Comment by devinmatte** [comment]
I'm seeing the issue on RHEL 7.7, RHEL 8.x and Fedora 30+, so yes fairly recent
