### ISSUE TITLE
GPG keys listed for the "Datadog, Inc

### ISSUE THREAD

**Issue by pradeepprakhar** [DataDog/puppet-datadog-agent#585]
I am getting this error.

`The GPG keys listed for the "Datadog, Inc." repository are already installed but they are not correct for this package.`

**Comment by albertvaka** [comment]
Which OS? Are you using the latest version of this module? And which version of the Agent are you trying to install?

**Comment by pradeepprakhar** [comment]
The OS is RHEL-7 and we are using below code to get it done.

```shell
if ! rpm -q datadog-agent; then
  yum makecache
  yum -y install datadog-agent
elif [ $(yum check-update datadog-agent >/dev/null 2>&1 ; echo $?) -eq 100 ] ; then
  yum makecache
  yum -y update datadog-agent
fi

cp /tmp/datadog.yaml /etc/datadog-agent/

systemctl enable datadog-agent
systemctl restart datadog-agent
```

**Comment by albertvaka** [comment]
Can you check if the latest version of the datadog puppet module fixes the issue?

**Comment by albertvaka** [comment]
@pradeepprakhar ping!

**Comment by albertvaka** [comment]
I'm going to close this issue. If you still have problems with Datadog signing keys, please refer to the docs on how to add the latest Datadog keys to the set of trusted keys on your system: https://docs.datadoghq.com/agent/faq/linux-agent-2022-key-rotation/
