### ISSUE TITLE
support for additional_endpoints

### ISSUE THREAD

**Issue by jvanbrunschot** [DataDog/puppet-datadog-agent#586]
Hi,

Since there is no clear migration path for moving from an US account to an EU account. We found out that the datadog config support a `additional_endpoints` configuration option. 

Like:

```
additional_endpoints:
  # one additional endpoint
  "https://app.datadoghq.eu": yourEUapikey 
```

Are you open for this (non official) method ?

**Comment by albertvaka** [comment]
Given `additional_endpoints` is an undocumented feature of the Agent, I'm a bit hesitant to add it as a config option to the puppet module. However, note that you can use `agent_extra_options` in puppet to add this and other options you might need that aren't explicitly supported by the module. Would that be enough for your use case?

**Comment by jvanbrunschot** [comment]
Thank you, that's exactly what we're looking for!

**Comment by albertvaka** [comment]
Happy that it helped!
