### ISSUE TITLE
Server Error: This Function Call is unacceptable as a top level construct in this location

### ISSUE THREAD

**Issue by Humbedooh** [DataDog/puppet-datadog-agent#593]
Line one in manifests/system_probe.pp (`include datadog_agent::params`) is causing puppet 6 to fail with the above message. As it seems like an unnecessary line (the other PPs don't have it), it should probably be removed. Tests with removing it work fine for us, and we cannot use DD's puppet module with the line in place.

**Comment by albertvaka** [comment]
Will be fixed in the next release.
