### ISSUE TITLE
$manage_repo not implemented for ubuntu agent

### ISSUE THREAD

**Issue by aderumier** [DataDog/puppet-datadog-agent#604]
Hi,

it seem that $manage_repo is missing from ubuntu agent. (I would like to use my own private repo).

Is it possible to add it ?

**Comment by jeremy-lq** [comment]
@aderumier Please open a support ticket so we can properly track this feature request, and notify you upon completion.

**Comment by albertvaka** [comment]
Hi @aderumier!

I've implemented this in https://github.com/DataDog/puppet-datadog-agent/pull/608 

Can you give it a try and let me know if it works for you?
