### ISSUE TITLE
[php-fpm] Integration missing fastcgi parameter

### ISSUE THREAD

**Issue by ChannoneArif-nbcuni** [DataDog/puppet-datadog-agent#606]
The use of fastcgi is documented here for php-fpm integration

https://docs.datadoghq.com/integrations/php_fpm/#unix-sockets

use_fastcgi = true

This is currently not a supported parameter in integrations/php_fpm.pp

**Comment by albertvaka** [comment]
Fixed (by yourself :) in https://github.com/DataDog/puppet-datadog-agent/pull/616
