### ISSUE TITLE
Can't set a logs_config to change logging to http from tcp/set compression

### ISSUE THREAD

**Issue by no-ones-there** [DataDog/puppet-datadog-agent#614]
**Desired outcome:** 
Option for a hash for logs_config under the init.pp so settings such as: 
- use_http: 
- use_compression: 
- compression_level: 

Can be used. This will enable for logging support through web proxies, tcp and socks proxies also. 

**Currently:** 
Although I may be wrong, there is currently no way to set log_config settings that are populated in the datadog.yaml file. 

**Current Workaround**
Adding a File to replace datadog.yaml, or adding a File-Line to change the settings on each puppet run.

**Comment by albertvaka** [comment]
Hi @no-ones-there!

For any options that don't have explicit parameters, you can use the `agent_extra_options` argument. This argument takes a dictionary that gets merged with the rest of the settings, so you can pass any setting you want to end up in `datadog.yaml`:
```
class { "datadog_agent":
    < your other arguments to the class >,
    agent_extra_options => {
        'use_http' => 'true',
        'use_compression' => 'true',
        'compression_level' => 'true',
    },
}
```

**Comment by no-ones-there** [comment]
Thanks, I am unable to test, but this option makes sense so I'll close off the issue.
