### ISSUE TITLE
system_probe

### ISSUE THREAD

**Issue by djtecha** [DataDog/puppet-datadog-agent#644]
is turning on the system_probe supported yet? Not seeing anything here for it.

**Comment by yeettaIT** [comment]
Hi, I use :
`  class { 'datadog_agent::system_probe':
    enabled => $network_monitoring,
  }`
which does the trick
/florus

**Comment by albertvaka** [comment]
As @yeettaIT said above, you can configure the system-probe by using the `datadog_agent::system_probe` class (which creates the `system-probe.yaml` config file). Does that work for you @djtecha ?
