### ISSUE TITLE
Setting tags in hiera isn't rendered correctly

### ISSUE THREAD

**Issue by djtecha** [DataDog/puppet-datadog-agent#651]
If I follow the docs and do something like this

```
datadog_agent::tags:
  - 'ip:%{ec2_metadata.local-ipv4}'
  - 'test:value'
```

It doesn't render correctly and results in stripping the quotes which breaks the datadog yaml

```
tags:
- ip:172.18.196.193
- test:value
```

**Comment by albertvaka** [comment]
What error do you get from the Agent when it parses the yaml with the tags unquoted? That seems valid yaml to me even without quotes.

**Comment by djtecha** [comment]
Turns out there was another issue occurring and the lack of indentation was throwing me off ass well. I'll close this.
