### ISSUE TITLE
excluded_interface_re gives error on evaluating the network.yaml.erb template

### ISSUE THREAD

**Issue by yeettaIT** [DataDog/puppet-datadog-agent#689]
Hi,
I include the class for network integration like : 
```
if $integrations_network_manage {
    include 'datadog_agent::integrations::network'
  }
```
and use hieradata to set the excluded_interface_re value as this:

```
datadog_agent::integrations::network::excluded_interface_re: 
    - vethwep.*
```

however this gives the following error:
```
Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template datadog_agent/agent-conf.d/network.yaml.erb:
  Filepath: /etc/puppetlabs/code/environments/host/modules/datadog_agent/templates/agent-conf.d/network.yaml.erb
  Line: 15
  Detail: undefined method `each' for nil:NilClass
 (file: /etc/puppetlabs/code/environments/host/modules/datadog_agent/manifests/integrations/network.pp, line: 57, column: 16) on node celery.vagrant.tricentsecurity.net
```

I can see from the code an array is needed so do not understand why I get the nil:NilClass error.

Any help appriciated!

/florus

**Comment by yeettaIT** [comment]
Ok, there is a type in https://github.com/DataDog/puppet-datadog-agent/blob/master/templates/agent-conf.d/network.yaml.erb
The excluded_interfaces_re.each should be excluded_interface_re.each (s removed).

Let me see if I can make a PR

/florus

**Comment by albertvaka** [comment]
Thanks a lot for investigating this and contributing a fix! 🍰 🚀
