### ISSUE TITLE
Add support for AlmaLinux

### ISSUE THREAD

**Issue by nbrys** [DataDog/puppet-datadog-agent#722]
Currently when using the module on AlmaLinux you get:

    amazon-ebs: Error: Evaluation Error: Error while evaluating a Function Call, Class[datadog_agent]: Unsupported operatingsystem: AlmaLinux (file: /tmp/packer-puppet-masterless/module-0/datadog_agent/manifests/params.pp, line: 67, column: 16) on node packer-syslog

**Comment by danoe** [comment]
Any update on this? With CentOS 8 non-Stream being EOL we're currently migrating everything to RockyLinux.

**Comment by albertvaka** [comment]
We ended up postponing this but this time for real we are going to implement this in the following weeks, sorry for the inconvenience 🙏

**Comment by StanvanHoorn** [comment]
@albertvaka Do you have any update on when a new release will be done with the support for Alma/Rocky?

**Comment by albertvaka** [comment]
Ooops! Thanks for the ping, I thought this had already happened. Releasing it now.

**Comment by StanvanHoorn** [comment]
Awesome! Thanks
