### ISSUE TITLE
Windows agent version isn't managed properly

### ISSUE THREAD

**Issue by benh57** [DataDog/puppet-datadog-agent#730]
I had dd installed (defaults to 'latest') but i wanted to enable NPM, so i specified the latest version via hiera to force an update:

`datadog_agent::agent_version: 7.35.1
`

The 7.35.1 gets used as part of the filename to download.

However, the agent actually installs as version 7.35.1.1, so this causes puppet to flap later:

`Notice: /Stage[main]/Datadog_agent::Windows/Package[Datadog Agent]/ensure: ensure changed '7.35.1.1' to '7.35.1' (corrective)`

If this fourth version# are always there, perhaps the url building code should ignore them?  Ie, let me specify 7.35.1.1 but then when it downloads, it could pull 7.35.1 but then use 7.35.1.1 as the version for the package resource.

**Comment by albertvaka** [comment]
Sorry for the late reply. This is indeed a bug, we will look into fixing it 🙇
