### ISSUE TITLE
find alternative for deprecated https://forge.puppet.com/modules/puppetlabs/ruby

### ISSUE THREAD

**Issue by fb-tricent** [DataDog/puppet-datadog-agent#735]
https://forge.puppet.com/modules/puppetlabs/ruby is a dependency but has been deprecated for over one year now. It would be good to find an alternative.

**Comment by ardrigh** [comment]
Also need an update on this because the deprecated ruby module which will cause problems for people looking to upgrade their Puppet environments.

**Comment by pillarsdotnet** [comment]
Why can't the datadog agent use the Puppet ruby instead of a separate system ruby?

**Comment by pillarsdotnet** [comment]
I'm going to try and fork the module and rework it to use Puppet ruby instead of system ruby.

**Comment by damonmaria** [comment]
Because of the dependency in puppetlabs-ruby we are now forced to be 2 major versions behind for stdlib. Which is now blocking us from upgrading common modules like puppetlabs-docker.

**Comment by ardrigh** [comment]
> I'm going to try and fork the module and rework it to use Puppet ruby instead of system ruby.

At the risk of adding a new dependency, there is this module https://github.com/puppetlabs-toy-chest/puppetlabs-puppetserver_gem which might be useful.

As best I can tell, the Ruby in this module is only there to install the reporting gem
