### ISSUE TITLE
Puppet is trying to reinstall windows datadog agent every Puppet run

### ISSUE THREAD

**Issue by evojay87** [DataDog/puppet-datadog-agent#743]
Hi, 

When we set puppet to install a particular version of the datadog agent on our Windows servers, Puppet seems to keep reinstalling the datadog agent every time a puppet run is done.

We have the following config in puppet hiera:
datadog_agent::agent_version: '7.29.0'

on the server when we are doing a puppet agent -t, we are seeing the following:

Notice: /Stage[main]/Datadog_agent::Windows/Package[Datadog Agent]/ensure: ensure changed '7.29.0.1' to '7.29.0'
Notice: /Stage[main]/Datadog_agent/File[C:/ProgramData/Datadog/datadog.yaml]/mode: mode changed '0760' to '0660'
Info: /Stage[main]/Datadog_agent/File[C:/ProgramData/Datadog/datadog.yaml]: Scheduling refresh of Service[datadogagent]
Error: Cannot start datadogagent, error was: Execution of 'C:/Windows/system32/net.exe start datadogagent' returned 2: The service is starting or stopping.  Please try again later.
Wrapped exception:
Execution of 'C:/Windows/system32/net.exe start datadogagent' returned 2: The service is starting or stopping.  Please try again later.
Error: /Stage[main]/Datadog_agent::Service/Service[datadogagent]/ensure: change from 'stopped' to 'running' failed: Cannot start datadogagent, error was: Execution of 'C:/Windows/system32/net.exe start datadogagent' returned 2: The service is starting or stopping.  Please try again later.
Notice: /Stage[main]/Datadog_agent::Service/Service[datadogagent]: Triggered 'refresh' from 1 event
Info: Class[Datadog_agent::Service]: Unscheduling all events on Class[Datadog_agent::Service]

**Comment by mx-psi** [comment]
Can you reproduce this with 3.17.0? Trying to see if this is related to #730

**Comment by evojay87** [comment]
After upgrading to version 3.17.0 this issue has been resolved for us.

looks like this bug fix resolve our issue :) - [BUGFIX] Use proper version string for package.ensure on Windows ([#741](https://github.com/DataDog/puppet-datadog-agent/issues/741))

**Comment by mx-psi** [comment]
That's great, glad this solved it for you :)
