### ISSUE TITLE
Improve the parameters for datadog.conf.erb

### ISSUE THREAD

**Issue by obowersa** [DataDog/puppet-datadog-agent#76]
At the moment a lot of the options within datadog.conf.erb aren't set as parameters. This leads to some headaches when trying to set up things such as dogstatsd.

Ideally all options within datadog.conf.erb should be able to be defined by parameters provided to the datadog_agent class. This would enable them to be declared where required without having to use a modified version of the puppet-datadog-agent module or override the file in a later module.

Additionally, it would be potentially worthwhile having all the parameters covered by the rspec-tests  in order to validate the default values and the custom ones. It would just provide a bit more confidence when introducing new parameters. 

This would probably need to take place as three parts:
- Existing parameters get tests added to the appropriate spec
- Tests are written up for the new parameters
- datadog_agent class and datadog.conf.erb are modified in order to pass the new parameters, with defaults matching the current setup in order to ensure the change is backwardly compatible.

**Comment by obowersa** [comment]
Something alone the lines of : https://github.com/obowersa/puppet-datadog-agent/tree/parameter_expansion potentially

**Comment by obowersa** [comment]
I've opend the following which covers all existing params ( I think!) https://github.com/DataDog/puppet-datadog-agent/pull/79

**Comment by albertvaka** [comment]
Fixed in https://github.com/DataDog/puppet-datadog-agent/pull/176
