### ISSUE TITLE
Error Setting Windows User

### ISSUE THREAD

**Issue by ADADarkpool** [DataDog/puppet-datadog-agent#805]
WE are trying to overide the default user to a domain user

from my understanding this should be merged into the code base 
https://github.com/DataDog/puppet-datadog-agent/pull/785

```
class {'datadog_agent':
 dd_user               => 'ddwinagentuser',
}
```
Returns error 

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement,
Evaluation Error: Error while evaluating a Resource Statement, Class[Datadog_agent]: has no parameter named 'dd_user' (file: /etc/puppetlabs/code/enviro
nments/XXX/modules/XXXX/manifests/datadog.pp, line: 35, column: 5) on XXXX
Warning: Not using cache on failed catalog`

Puppet module version 3.22

**Comment by shbakesas** [comment]
You want     
class { 'datadog_agent':
  windows_ddagentuser_name  => $windows_ddagentuser_name,
}

**Comment by ADADarkpool** [comment]
That did it, thank you!
